packages:
    - 'packages/*'
    - 'apps/*'

catalog:
  '@primeuix/styled': ^0.5.0
  '@primeuix/utils': ^0.5.1
  '@primeuix/forms': ^0.0.4
  '@primeuix/styles': ^0.1.0-beta.3
  '@primeuix/themes': ^0.1.0-beta.6
